
####################################################################################################
# Argo CD Build stage which performs the actual build of Argo CD binaries
####################################################################################################
FROM harbor.yf-online.service.163.org/golang/golang:1.21 as argocd-build
ENV GOPROXY=https://goproxy.cn,direct

COPY ./packr_1.21.9_linux_amd64.tar.gz /tmp/
RUN tar -zxvf /tmp/packr_1.21.9_linux_amd64.tar.gz -C /tmp/ && \
    mv /tmp/packr /usr/local/bin/packr

WORKDIR /go/src/github.com/argoproj/argo-cd

COPY . .

RUN go mod download
RUN make controller

####################################################################################################
# Final image
####################################################################################################
FROM hub-inner.cn-east-p1.netease.com/staffyun163music/cloudnative/argocd/argoproj/argocd:v1.7.6 as base
COPY --from=argocd-build /go/src/github.com/argoproj/argo-cd/dist/argocd-application-controller /usr/local/bin/
